### ISSUE TITLE
Changing local time will affect the server time ?

### ISSUE THREAD

**Issue by mohamedpsx** [NodeGuy/ServerDate#16]
i don't know if this is a bug or this is how the script work, but when you change your local time to inferieur time from the server time, the server time changes.

Any ideas why ? and if this is normal or not ? because i think it is not normal and server time should not be affected.

Thank you

**Comment by curby** [comment]
If we assume that the server clock will be more or less constant but the client clock may change, then any changes in client clock should trigger a resync.  

Possible solution: each time the client time is gathered for display on the web page, detect changes in client clock (compare "current" to "last").  If the changes are outside of a given threshold (say -1s to +3s when we expect +1s difference between "current" and "last"), assume that the clock changed and that a rsync is needed.

Since ServerDate largely "inherits" from Date's functions, some of these may need to be "overloaded" to include the above change detection logic.

Edge/unusual cases: 
  1.  Computer sleep/resume may trigger a resync, but this is probably a good thing
  1.  DST changes on client may trigger a (possibly unnecessary) resync

I haven't gone through the code to check if this is already possible, but an externally-accessible state variable would be nice, so the web page can display whether or not the JS engine is synchronizing, not synchronizing, or perhaps in another state (e.g. need to sync due to client clock change).  This also may belong in another issue/request.

**Comment by NodeGuy** [comment]
If someone cares about this enough I'm open to discussing a pull request.
